### ISSUE TITLE
Seems not to work for gradio 5.6.0

### ISSUE THREAD

**Issue by dreylago** [openanalytics/shinyproxy-gradio-demo#1]
I am trying to use ShinyProxy for a Gradio application.

This simple example does not work for Gradio version 5.6.0:

Incorrect GET request due to a malformed URL for /index-<xxx..>.css.
Incorrect GET request due to a malformed URL for /theme.css.
Incorrect POST request due to a malformed URL for .../queue/join?
All of these requests seem to have their root path missing.

All other elements appear to have the correct root path.

Gradio version: 5.6.0.

I am not sure if this is an issue with ShinyProxy or Gradio. 

Any pointers would be welcome.

**Comment by LEDfan** [comment]
Hi, thank you for opening this issue! It seems this is caused by an issue in gradio: https://github.com/gradio-app/gradio/issues/7934

However, by adding the following config to ShinyProxy it works again:

```
- id: gradio-demo
  # ....
 container-env:
    GRADIO_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH').replaceFirst('/$','')}"
```

I updated the README and also pushed a new version of the image which uses gradio 5.8.0. Could you give this a test?
